name: perform the dispatch
on: workflow_dispatch

jobs:
  send-dispatch:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
      metadata: read

    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: dispatch bitches
        uses: ./.github/actions/local-action
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
